# Materiały pomocnicze
* https://www.tutorialspoint.com/python/index.htm
* http://cs231n.github.io/python-numpy-tutorial/

# Dlaczego Python do uczenia maszynowego?


*   Dosyć dobre wsparcie dla obiektowości pozwala tworzyć szybko biblioteki: Bardzo dużo użytecznych : numpy/tensroflow/keras/gensim
*   Interpretowalność i dynamiczna kontorla typów pozwala na szybkie protytopowanie małych projektów. Dla większych projektów staje się to przeszkodą 
*   W porównaniu do R do można używać Pythona od razu na produkcji. 
* Bardzo duża społeczność (więcej materiałów/bibliotek, łatwiej uzyskać odpowiedź na pytanie)



  
  
 

# Którego IDE używać?


* PyCharm - pełnoprawne środowisko od JetBrains:
  * posiada świetny debbugger - przydatne jeśli chcemy przeanalizować fragent kodu, który nieznamy
  * środowisko "data sciene" (niestety wciąż dosyć kiepskie)
  * istnieje możliwość uruchamiania części kodu, jednak wciąż kiepskie
* Jupyter Notebook:
  * Lokalnie/Przeglądarka: 
    * można używać wszędzie (nawet na telefonie)
    * ale brakuje debuggera
  * JupyterLab - TODO: write info
  * Colab - trochę bardziej rozszerzona przeglądarka:
    * można współpracować z kolegami
    * można używać apt-get oraz pip
    * karta graficzna k80 za darmo
    
Czego używać?
Do większych projektów PyCharm. Do mniejszych jupyter lab/jupyter notebook

# Uzyskiwanie pomocy

Python pozwala na uzyskanie pomocy z interpetera:

help(obiekt) - uzycie obiekt

dir(obiekt) - pokaz wszystkie dostepne metody 

In [0]:
help(print)

In [0]:
dir(print)

In [0]:
# Operatory:

assert 2 + 3 == 0 # dodawanie
assert 2 * 3 == 0 # mnozenie
assert 2 ** 3 == 0 # potegowanie
assert 2 / 3 == 0 # dzielenie z reszta
assert 2 // 3 == 0 # dzielenie calkowite

# W pythonie nie istnieją operatory inkrementacji/dekrementacji

# Zadanie 1 (0 pkt)
Napraw asserty

In [0]:
# Operatory przypisania:
x = 3 # przypisanie
x += 3 # dodawanie z przypisaniem
x -= 3 # odejmowanie z przypisaniem
x *= 3 # mnozenie z przypisanie
x /= 3 # dzielenie z przypisaniem
x 

# Pytanie 1 (0 pkt)
Dlaczego x zmienił typ na zmienno przecinkowy?

# Bloki
W pythonie nawiasy {} (c++/java) są zastąpione pzrez wcięcia (spacje/tabulatory). Twórcy języka zdecydowali tak, aby użytkownik od początku uczył się poprawnego formatowania kodu. Często sprawia to problemy, jak np. otwieramy kod w innym edytorze, albo kopiujemy kod z innego źródła.

# Funkcje
Funkcje tworzy używając def oraz bloku, można podawać do funkcji domyślne argumenty


```
def increment(x=0):
  return x+1
```



# Najważniejsze typy danych:

Konstruktor/operator języka konstruktor

* dict()/{klucz: wartosc} - Słownik. Mapa w Javie - szybkie odwolywanie
* set()/{} - Zbiór. 
* list/()[] - Lista
* tuple()/() - krotka
* "abc"/'abc' - string

# Listy

Może składać się z elementów różnego typu, np. str, intów

Odwoływanie się do listy:

* mylist[0] - zerowy element
* mylist[0:2] - wycinek (slice) listy zerowy i pierwszy element, slice
* mylist[-1] - ostatni element listy
* mylist[:3] - wszystkie elementy do 3 elementu
* mylist[2:] - wszystkie elementy od drugiego
* mylist[::2] - co drugi element
* mylist[::-1] - odwróć listę

Inne operatory:
* mylist1 + mylist2 - nowa lista składająca się z 2 poprzednich
* mylist * 3 - powiela listę 3 razy
* mylist[4] = 0 - przypisuje do na 4 pozycję element 0
* len(mylist) - zwraca długość listy
* 4 in mylist - sprawdza czy 4 znajduje się w liście


# Zadanie 2 (0 pkt)

Uzupełnij aserty

In [0]:
mylist = [1, ["a", "b"], "abc", 2]

assert mylist[0] == 0
assert mylist[0:2] == 0
assert mylist[-1] == 0
assert myslist[::2] == 0
assert mylist + [3, 4] == 0
assert mylist * 3 == 0

mylist[3] = 5


assert len(mylist) == 0
assert 4 in mylist

# Zadanie: palindrom (0 pkt)

Napisz w jednej linijce sprawdzenie, czy x (lista) jest palindromem, używając tylko operatora dostępu


#Tuple

Krotka (tuple) - zachowuje sie praktycznie jak lista tylko, nie można zmieniać wartości. Najczęściej używane jeśli chcemy zwrócić coś w funkcji lub przekazać jako argument.

# Słownik

Mapa postaci klucz <-> wartość. O(1) czas dostępu. Od Pythona 3.5 lub 3.6 domyślnie klucze są posortowane. Bardzo przydatne, tak samo jak lista.


```
dict() - pusty słownik
{'key': 'value'} - slownik z kluczem key oraz wartoscia value
mydict.keys() - zwraca klucze jako listę
mydict.values() - zwraca wartości jako listę
mydict.items() - zwraca listę tupli (klucz, wartość)

```

# Zadanie: asserty słownik (0 pkt)
Uzupełnij asserty

In [0]:
import unittest
mydict = {0: 'a'}
mydict[1] = 'b'


assert mydict[0] == 0

assert sorted(mydict.keys()) == 0
assert sorted(mydict.values()) == 0
assert sorted(mydict.items()) == 0


# Zadanie: counter (0 pkt)

Napisz funkcję, która przyjmuje listę a zwraca słownik z policzoną ilością poszczególnych elementów. Np. 

```
counter(['a', 'b', 'b']) -> {'a': 1, 'b': 2}
```

W pythonie istnieje klasa collections.Counter, która robi to samo

In [0]:
def counter(l):
  return l

l = ['a', 'b', 'b']
assert counter(l) == {'a': 1, 'b': 2}

# Stringi

str(obiekt) - tworzy string na podstawie obiektu. String w pythonie zachowuje się podobnie jak lista, czyli można:

```
mystring = "abc"
mystring[0] -> "a"
```

```
"x wynosi: {}".format(3) - podstawia wszystkie wystąpienia {} przez argument
```

In [0]:
mystring = "abc"
assert mystring + "def" == 0
assert mystring[0] == 0
assert "x: {}".format(0) == 0

# Control statement

Nie ma nawiasów, tylko spacje oraz nawiasy

# If
if/elif/else oraz wcięcia

Nie istnieje jednak operator switch, zazwyczaj się zastępuje poprzez if/elif

Operator logiczny jest pisany slowami: and (&&) oraz or (||)

# Pętle


for - używa iterowanie najczęściej po liście, więc jest to bardziej pętla for each. Można iterować jak w c++ używając funkcji range()

while - podobnie jak c++/java:


In [0]:
password = "secret"
if password == "secret" or password == "secret1":
  print('Know my secret')
elif passowrd == "password":
  print("You know my other password")
else:
  print("You don't know any of my password")

In [0]:
start = 0
step = 2
end = 4
list(range(start, end, step)) # zwraca listę od start to end używając kroku step

In [0]:
for i in range(4):
  print(i)
  
i = 0
while i < 4:
  print(i)
  i += 1

In [0]:
class Person:
  pass # pass jest uzywane jesli mamy blok, a nie chcemy w nic zawrzeć

class Student(Person):
  #klasa student jest dziedziczona po person
  class_variable = 0 
  
  def __init__(self, name):
    self.name = name
    #konstruktor - self aktualny obiekt
    self.knowledge = 0 
  
  def learn(self):
    # aktualny obiekt 
    self.knowledge += 1
  
  @staticmethod
  def static_method():
    # metoda statyczna
    print(Student.class_variable)
  
  
s1 = Student("Karol")
s2 = Student("Piotr")

s1.learn()
Student.class_variable += 1
Student.static_method()
Student.name = "Piotr Jozef"

#Exceptions 


In [0]:
def divide(x):
    try:
        # Division by zero raises an exception
        x = x / 0
    except ZeroDivisionError:
        # We are trying to catch specific type of exception, we catch multiple exceptions
        print("Oops, invalid.")
    else:
        pass
        # Otherwise
    finally:
        # This is executed after the code block is run
        # and all exceptions have been handled, even
        # if a new exception is raised while handling.
        print("We're done with that.")
     

# Zadanie: sortowanie + pkt

Zaimplementuj dowolne sortowanie działający w czasie O(n^2)

# Inne operatory


In [0]:
string = "abc"
type(string) # zwraca typ danych


In [0]:
from math import *

print(ceil(4.7)) # zwraca sufit liczby rzeczywistej
print(floor(4.7)) # zwraca podłogę liczby rzeczywistej
print(fabs(-3)) # zwraca wartość absolutną liczby rzeczywistej
print(modf(2.5)) # zwraca krotkę zawierającą część ułamkową i całkowitą liczby rzeczywistej
print(exp(2)) # zwraca e do potęgi x
print(log(e)) # zwraca logarytm naturalny
print(log(8, 2)) # zwraca logarytm o podstawie 2 (drugi parametr)
print(sqrt(2.25)) # zwraca pierwiastek kwadratowy
print(cos(1))

# Ankieta

In [22]:
f = lambda x: x+10 # tworzy funkcje lambda (tak jakby inline), można używać jeśli potrzebuje
[(i+10)*3 for i in range(5)] # list comprehension - szybsze tworzenie pętli, których wynikiem jest lista
{(i+2)/2 for i in range(5)} # set comprehension - szybsze tworzenie petli, których wynikiem jest set

{1.0, 1.5, 2.0, 2.5, 3.0}

# Numpy

Numpy - jest biblioteka do obliczeń numerycznych, używa się podobnie jak matlaba


Większość kodów pochodzi z: http://cs231n.github.io/python-numpy-tutorial/

In [0]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

# Tworzenie macierzy

In [0]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"


In [0]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

In [0]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

In [0]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

In [0]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

In [0]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

In [0]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

In [0]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [0]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

In [0]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

In [0]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [0]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [0]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

# Zadania: numpy1 + pkt (za zrobienie większości)

Jeśli macierz nie jest określona przyjmij macierz dowolnego rozmiaru

1. Znormalizuj (średnia 0, wariancja 1) losowa macierz 5x5
1. Stwórz macierz 4x4 typu bool, true na przekątnej
1. Wybierz parzyste elementy z losowego wektora 5x5
1. Z wektora [1 .. 10] zastąp parzyste elementy przez 0
1. Utwórz [1 .. 100 ] rozmiaru 10 x 10
1. Połącz ze sobą 2 wektory horyzontalnie
1. Znajdź wspólne elementy w 2 losowych wektorach 10 x 1 (intersect1d)
1. W losowej macierzy 10 x 10 zamień ze sobą 0 i 3 kolumnę (slicing)
1. Wypisz wektor 20 x 1, wypisują wszystkie liczby (bez ucinania) (np.set_printoptions)
1. Wygeneruj macierz floatów w przedziale 4x4

# Zadania: numpy2 + pkt (za zrobienie większości)

1. Odejmij od każdej kolumny średnią kolumny
2. Znajdź najbliższą wartość w macierzy (A) do podanej wartości (x)
3. W macierzy 20x20 znajdź sumę w bloków, rozmiar bloku (5x5)

Więcej zadań (może częśc odpowiedzi nawet):

1. https://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html
1. https://www.machinelearningplus.com/101-numpy-exercises-python/